config/routes.rb
Rails.application.routes.draw do
  resources :contacts_events
  resources :contact_events
  resources :events
  resources :contacts
  devise_for :users, :controllers => {
    :omniauth_callbacks => "users/omniauth_callbacks",
  }

  root 'application#default'

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  STATES = %w{ WA OR ID }.sort

  SALUTATIONS = [
    'Mr. & Mrs.',
    'Mr.',
    'Ms.',
    'Mrs.',
    'Mr. & Mr.',
    'Mrs. & Mrs.',
    'Ms. & Ms.',
  ].sort

  has_and_belongs_to_many :events

  def name
    [ salutation, first_name, last_name ].join(' ')
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to contacts_path, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to contacts_path, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:salutation, :first_name, :last_name, :street, :apt, :city, :state, :zip)
    end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.haml
= form_for @contact do |f|
  - if @contact.errors.any?
    #error_explanation
      %h2= "#{pluralize(@contact.errors.count, "error")} prohibited this contact from being saved:"
      %ul
        - @contact.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :salutation
    = f.select :salutation, Contact::SALUTATIONS.unshift(nil)
  .field
    = f.label :first_name
    = f.text_field :first_name
  .field
    = f.label :last_name
    = f.text_field :last_name
  .field
    = f.label :street
    = f.text_field :street
  .field
    = f.label :apt
    = f.text_field :apt
  .field
    = f.label :city
    = f.text_field :city
  .field
    = f.label :state
    = f.select :state, Contact::STATES
  .field
    = f.label :zip
    = f.number_field :zip
  .actions
    = f.submit 'Save'

app/views/contacts/edit.html.haml
%h1 Editing contact

= render 'form'

= link_to 'Show', @contact
\|
= link_to 'Back', contacts_path

app/views/contacts/index.html.haml
%h1
  Listing
  = pluralize(@contacts.count, 'contacts')

%table.table.table-hover
  %thead
    %tr
      %th
      %th Salutation
      %th First name
      %th Last name
      %th Street
      %th Apt
      %th City
      %th State
      %th Zip
      %th
      %th
      %th

  %tbody
    - @contacts.each do |contact|
      %tr
        %td= contact.id
        %td= contact.salutation
        %td= contact.first_name
        %td= contact.last_name
        %td= contact.street
        %td= contact.apt
        %td= contact.city
        %td= contact.state
        %td= contact.zip
        %td= link_to 'Show', contact
        %td= link_to 'Edit', edit_contact_path(contact)
        %td= link_to 'Destroy', contact, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Contact', new_contact_path

app/views/contacts/new.html.haml
%h1 New contact

= render 'form'

= link_to 'Back', contacts_path

app/views/contacts/show.html.haml
%p#notice= notice

%h3= @contact.name

%p
  %b Salutation:
  = @contact.salutation
%p
  %b First name:
  = @contact.first_name
%p
  %b Last name:
  = @contact.last_name
%p
  %b Street:
  = @contact.street
%p
  %b Apt:
  = @contact.apt
%p
  %b City:
  = @contact.city
%p
  %b State:
  = @contact.state
%p
  %b Zip:
  = @contact.zip

= link_to 'Edit', edit_contact_path(@contact)
\|
= link_to 'Back', contacts_path

%h3= pluralize(@contact.events.count, 'Event')

%ol
  - @contact.events.each do |event|
    %li= link_to event.name, event