config/routes.rb
Rails.application.routes.draw do
  resources :contacts_events
  resources :contact_events
  resources :events
  resources :contacts
  devise_for :users, :controllers => {
    :omniauth_callbacks => "users/omniauth_callbacks",
  }

  root 'application#default'

end

app/models/contacts_event.rb
class ContactsEvent < ActiveRecord::Base
  belongs_to :contact
  belongs_to :event
end

app/controllers/contacts_events_controller.rb
class ContactsEventsController < ApplicationController
  before_action :set_contacts_event, only: [:show, :edit, :update, :destroy]

  # GET /contacts_events
  # GET /contacts_events.json
  def index
    @contacts_events = ContactsEvent.all
  end

  # GET /contacts_events/1
  # GET /contacts_events/1.json
  def show
  end

  # GET /contacts_events/new
  def new
    @contacts_event = ContactsEvent.new
  end

  # GET /contacts_events/1/edit
  def edit
  end

  # POST /contacts_events
  # POST /contacts_events.json
  def create
    @contacts_event = ContactsEvent.new(contacts_event_params)
    puts contacts_event_params
    puts @contacts_event.inspect

    respond_to do |format|
      if @contacts_event.save
        format.html { redirect_to @contacts_event, notice: 'Contacts event was successfully created.' }
        format.json { render :show, status: :created, location: @contacts_event }
      else
        format.html { render :new }
        format.json { render json: @contacts_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts_events/1
  # PATCH/PUT /contacts_events/1.json
  def update
    respond_to do |format|
      if @contacts_event.update(contacts_event_params)
        format.html { redirect_to @contacts_event, notice: 'Contacts event was successfully updated.' }
        format.json { render :show, status: :ok, location: @contacts_event }
      else
        format.html { render :edit }
        format.json { render json: @contacts_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts_events/1
  # DELETE /contacts_events/1.json
  def destroy
    @contacts_event.destroy
    respond_to do |format|
      format.html { redirect_to contacts_events_url, notice: 'Contacts event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contacts_event
      @contacts_event = ContactsEvent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contacts_event_params
      params.require(:contacts_event).permit(:contact_id, :event_id)
    end
end

app/helpers/contacts_events_helper.rb
module ContactsEventsHelper
end

app/views/contacts_events/_form.html.haml
= form_for @contacts_event do |f|
  - if @contacts_event.errors.any?
    #error_explanation
      %h2= "#{pluralize(@contacts_event.errors.count, "error")} prohibited this contacts_event from being saved:"
      %ul
        - @contacts_event.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :contact
    = f.collection_select :contact_id, Contact.all, :id, :first_name
  .field
    = f.label :event
    = f.collection_select :event_id, Event.all, :id, :name
  .actions
    = f.submit 'Save'

app/views/contacts_events/edit.html.haml
%h1 Editing contacts_event

= render 'form'

= link_to 'Show', @contacts_event
\|
= link_to 'Back', contacts_events_path

app/views/contacts_events/index.html.haml
%h1 Listing contacts_events

%table
  %thead
    %tr
      %th Contact
      %th Event
      %th
      %th
      %th

  %tbody
    - @contacts_events.each do |contacts_event|
      %tr
        %td= contacts_event.contact
        %td= contacts_event.event
        %td= link_to 'Show', contacts_event
        %td= link_to 'Edit', edit_contacts_event_path(contacts_event)
        %td= link_to 'Destroy', contacts_event, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Contacts event', new_contacts_event_path

app/views/contacts_events/new.html.haml
%h1 New contacts_event

= render 'form'

= link_to 'Back', contacts_events_path

app/views/contacts_events/show.html.haml
%p#notice= notice

%p
  %b Contact:
  = @contacts_event.contact.name
%p
  %b Event:
  = @contacts_event.event.name

= link_to 'Edit', edit_contacts_event_path(@contacts_event)
\|
= link_to 'Back', contacts_events_path