config/routes.rb
Rails.application.routes.draw do
  resources :contacts_events
  resources :contact_events
  resources :events
  resources :contacts
  devise_for :users, :controllers => {
    :omniauth_callbacks => "users/omniauth_callbacks",
  }

  root 'application#default'

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{ charset: "utf-8" }
    %meta{ "http-equiv": "X-UA-Compatible", content: "IE=edge" }
    %meta{ name: "viewport", content: "width=device-width, initial-scale=1" }
    %title Mail List
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-default
      .container
        .navbar-header
          = link_to 'Mail List', root_path, class: 'navbar-brand'
        %ul.nav.navbar-nav
          %li= link_to 'Contacts', contacts_path
          %li= link_to 'Events', events_path
        %ul.nav.navbar-nav.navbar-right
          - if user_signed_in?
            %li= link_to 'Sign out', destroy_user_session_path, method: :delete
          - else
            %li= link_to 'Sign in', new_user_session_path

    .container
      .row
        .col-sm-12
          - flash.to_h.each_pair do |name, value|
            .alert.alert-info.alert-dismissable{role: 'alert'}
              %button.close{type: 'button', 'data-dismiss': 'alert', 'aria-label': 'Close'}
                %span{'aria-hidden':true} &times;
              %strong= name.capitalize
              = value
    .container
      .row
        .col-sm-12
          = yield